services:
  - type: web
    name: dklautomationgo
    runtime: docker
    plan: starter
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: ALLOWED_ORIGINS
        value: https://dekoninklijkeloop.nl
      - key: DEV_MODE
        value: "false"
      - key: SMTP_HOST
        value: smtp.hostnet.nl
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: INFO_EMAIL_PASSWORD
        sync: false
      - key: INSCHRIJVING_EMAIL_PASSWORD
        sync: false
      - key: NOREPLY_EMAIL_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: dkl_db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: dkl_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: dkl_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dkl_db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: dkl_db
          property: port
      - key: DB_SSLMODE
        value: require
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRY
        value: 15m
      - key: JWT_REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: PASSWORD_MIN_LENGTH
        value: "8"
      - key: PASSWORD_REQUIRE_UPPERCASE
        value: "true"
      - key: PASSWORD_REQUIRE_LOWERCASE
        value: "true"
      - key: PASSWORD_REQUIRE_NUMBER
        value: "true"
      - key: PASSWORD_REQUIRE_SPECIAL
        value: "true"
      - key: GIN_MODE
        value: "release"
      - key: TZ
        value: "Europe/Amsterdam"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

databases:
  - name: dkl_db
    databaseName: dkl_production
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all 